### PR TITLE
fix: convert to linux line endings

### PR DESCRIPTION
**Pull request by dylanmedlin**
This PR fixes issues running the main.rb script due to missing a new line between hashbang statement and script body

### CODE REVIEW

**Comment by allanfarrell** [comment]
Please add more information to clarify what is required.
Does WSL need to be installed? Is this covered in the Docker Desktop instructions?
Where are you running the command from? command prompt? powershell? wsl?
Need to be in the splashkit-translator directory to run the command.

Try to make it so that no questions need to be asked to follow the process.

**Comment by dylanmedlin** [comment]
All Docker Desktop instructions (how to install and use) are provided during the installation of Docker Desktop. Including the installation instructions here would be redundant, also if there were changes to their installation instructions we would not know, and ours may become outdated.

**Comment by allanfarrell** [comment]
Sorry, didn't mean include those instructions.
I wasn't sure what I mentioned was already covered by the Docker instructions.
Agree that we shouldn't duplicate them.

**Comment by dylanmedlin** [comment]
I have made a new commit that uses .gitattributes to force all Ruby files to have LF line endings regardless of local git settings. Which should fix the issue of it converting back to CRLF when cloning to a windows machine

**Comment by dylanmedlin** [comment]
**Instructions to run the translator on Windows:**

1.  Install Docker Desktop
- The installation should walk you through installing WSL2 as well
- Also no need to install any subsystem OS as we won't need it

2. Clone this PR

3. Open command prompt from the repo directory
- Just the default Windows Command Prompt or PowerShell
	
4. Run `docker build --tag headerdoc -f Dockerfile .` to build the image		
- This must be run from the repo's root directory
	
5. Run `docker run --rm -v <absolute path to splashkit-core>:/splashkit/ headerdoc ./src/main.rb -i /splashkit/ -o /splashkit/generated -g cpp,docs,clib,python,pascal,csharp`
- Replace `<absolute path to splashkit-core>` with the splashkit-core directory
- Can run this command from any location, doesn't need to be from the translators directory

**Comment by tancnle** [comment]
Thanks, @dylanmedlin. I am looking into it now.

**Review by allanfarrell — APPROVED** [review]
The changes look good. I have tested this branch and instructions and have it working.

**Review by tancnle — APPROVED** [review]
Thanks, @dylanmedlin. The change looks good to me 👍🏼 🚀

**Pull request merged**
