### PR TITLE
Feat/ubuntu setup script

### PR DESCRIPTION
**Pull request by allanfarrell**
A bash script to setup a development environment for working on the SplashKit translator in Ubuntu.

### CODE REVIEW

**Review by Xiphias5985 — CHANGES_REQUESTED** [review]
Script tested with Allan on a clean Ubuntu install. Changes discussed regarding additional command lines and some -y automation to be implemented.

**Comment by allanfarrell** [comment]
Added additional commands to configure the docker repository correctly and added automatic reply for Git install.

**Comment by allanfarrell** [comment]
Thanks Ben!

Added additional commands to configure the docker repository correctly and added automatic reply for Git install.

**Review by Xiphias5985 — APPROVED** [review]

**Comment by jacksievers** [comment]
Just had a look at the script, seems to be fine, includes all the necessary parts that need to be installed on Ubuntu for the translator to function properly.

**Review by wil-saman — APPROVED** [review]
Tested on a clean Linux install on Oracle VM. The setup was seamless and all the necessary files are included to get the translator working.

**Review by jacksievers — APPROVED** [review]
Left comment above but includes everything that is needed for this translator to work on Ubuntu

**Pull request merged**
