### PR TITLE
fix: modernise ruby toolchain 

### PR DESCRIPTION
**Pull request by tancnle**
This PR updates the Ruby toolchains to `2.7.5`.

- Set Ruby version to `2.7.5`
- Update all dependencies
- Set bundle version to v2 (v1 has already been deprecated)

## How to test

- Check out the branch
- Make sure to use a [Ruby Version Manager](https://github.com/rbenv/rbenv) to install Ruby 2.7.5 (do not use the one that comes with macOS)
- Run `bundle install`
- Verify the translator run successfully
  ```sh
  ./translate -i ../splashkit-core -o ~/Desktop/translated -g PYTHON
  ```
- This takes a while (~ 45.67s on my computer)
- Verify the file content
  ```sh
  ❯ wc -l ~/Desktop/translated/python/splashkit.py
  8904 /Users/tanle/Desktop/translated/python/splashkit.py
  ```
Tested on macOS 12.3.1 (Monterey) and XCode 13.3 (13E113)

### CODE REVIEW

**Comment by tancnle** [comment]
👋🏼 @macite I would love to seek your expertise on this PR, please 🙏🏼

**Comment by macite** [comment]
@tancnle this looks fine to me. I'd be happy to merge it into the main repo.

**Comment by tancnle** [comment]
Thanks, @macite. That would be great 👍🏼 

@allanfarrell @dylanmedlin Any thoughts? We need 2 approvals as per our company [guideline](https://github.com/thoth-tech/handbook/blob/main/docs/processes/quality-assurance/git-contribution-guide.md#required-approvals) before I can merge this.

**Review by allanfarrell — APPROVED** [review]
Looks good.

**Review by dylanmedlin — APPROVED** [review]

**Comment by tancnle** [comment]
Thanks for reviewing @allanfarrell @dylanmedlin and @macite 🙇🏼

**Comment by dylanmedlin** [comment]
Can confirm this works on macOS 10.15.7
Screen Shot 2022-04-11 at 12 29 07 am

**Pull request merged**
